# Inspecting normalizations

## TODOs


- [ ] Use functions defined elsewhere instead of the stuff copied here (e.g. `CustomNormalizer`)
- [ ] Write some explanations and describe observations
- [ ] Use test data from before 1600 and after 1900
- [ ] Perhaps include a sym-diff to display where the texts differ on the character-level

In [11]:
import datasets
import os
import torch
import transformers
from tokenizers.normalizers import Normalizer
from tokenizers import NormalizedString

In [8]:
# number of paragraphs per split (= century)
N = 100

In [21]:
# Load DTA validation split for three time periods
datadir = "/home/bracke/data/dta/dtak/"
data_files = {
    "1600to1699": os.path.join(datadir, "dta-ps-1600-1699-validation.jsonl"),
    "1700to1799": os.path.join(datadir, "dta-ps-1700-1799-validation.jsonl"),
    "1800to1899": os.path.join(datadir, "dta-ps-1800-1899-validation.jsonl"),
}
ds = datasets.load_dataset("json", data_files=data_files)


ds["1600to1699"] = ds["1600to1699"].shuffle().select(range(N))
ds["1700to1799"] = ds["1700to1799"].shuffle().select(range(N))
ds["1800to1899"] = ds["1800to1899"].shuffle().select(range(N))

ds = ds.rename_column("text", "orig")

Using custom data configuration default-86e8bd6a081066fa
Found cached dataset json (/home/bracke/.cache/huggingface/datasets/json/default-86e8bd6a081066fa/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|██████████| 3/3 [00:00<00:00, 77.73it/s]

In [18]:
# GPU set-up
device = torch.device('cuda:1' if torch.cuda.is_available() else "cpu")

# Load model
checkpoint = "/home/bracke/code/transnormer-old/models/models_2023-02-14_12-29/checkpoint-44000"
model = transformers.EncoderDecoderModel.from_pretrained(
    checkpoint, 
    ).to(device)

# Load tokenizer
class CustomNormalizer:
    def normalize(self, normalized: NormalizedString):
        normalized.nfd() # unicode decomposition
        normalized.replace("ſ", "s")
        normalized.replace("ꝛ", "r")
        normalized.replace(chr(0x0303), "") # drop combining tilde
        normalized.replace(chr(0x0364), "e")
        normalized.replace("æ", "ae")
        normalized.replace("ů","ü")
        normalized.replace("Ů","Ü")
        normalized.nfc()

tokenizer_hmbert_custom = transformers.AutoTokenizer.from_pretrained("dbmdz/bert-base-historic-multilingual-cased")
tokenizer_hmbert_custom.backend_tokenizer.normalizer = Normalizer.custom(CustomNormalizer())
tokenizer_bert = transformers.AutoTokenizer.from_pretrained("bert-base-multilingual-cased")

In [23]:
def generate_normalization(batch):
    inputs = tokenizer_hmbert_custom(batch["orig"], padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    input_ids = inputs.input_ids.to(device)
    attention_mask = inputs.attention_mask.to(device)

    outputs = model.generate(input_ids, attention_mask=attention_mask)

    output_str = tokenizer_bert.batch_decode(outputs, skip_special_tokens=True)

    # batch["norm_pred_ids"] = outputs
    batch["norm_pred_str"] = output_str

    return batch


ds = ds.map(
    generate_normalization, 
    batched=True, 
    batch_size=8, 
    )

  0%|          | 0/25 [00:00<?, ?ba/s]/home/bracke/miniconda3/envs/gpu-venv-transnormer/lib/python3.9/site-packages/transformers/generation/utils.py:1186: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/bracke/miniconda3/envs/gpu-venv-transnormer/lib/python3.9/site-packages/transformers/generation/utils.py:1273: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 128 (`generation_config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
100%|██████████| 25/25 [01:01<00:00,  2.47s/ba]
100%|██████████| 25/25 [00:56<00:00,  2.28s/ba]
100%|██████████| 25/25 [00:58<00:00,  2.36s/ba]

In [33]:
import pandas as pd
# don't truncate cells with long text
pd.set_option('display.max_colwidth', None)

part = "1600to1699"
df1600to1699 = pd.DataFrame(data={"orig" : ds[part]["orig"], "norm_pred" : ds[part]["norm_pred_str"]})
part = "1700to1799"
df1700to1799 = pd.DataFrame(data={"orig" : ds[part]["orig"], "norm_pred" : ds[part]["norm_pred_str"]})
part = "1800to1899"
df1800to1899 = pd.DataFrame(data={"orig" : ds[part]["orig"], "norm_pred" : ds[part]["norm_pred_str"]})

## Inspect dataframes

### 1600 to 1699

In [ ]:
df1600to1699.head(20)

### 1700 to 1799

In [34]:
df1700to1799.head(20)

,orig,norm_pred
0,"† Entfuͤhrung der Europa, ein antikes Moſaik.","1führung der Europa, ein antikes Mosaik."
1,"Die langen jambiſchen Verſe mit ungetrennten Reimen ſchicken ſich am beſten dazu, man mag ſie nun entweder in einem hintereinander fort laufen laſſen, und nur zuweilen an bequemen Orten einen Abſatz machen, oder auch acht oder zehnzeilichte Strophen machen, wie Neukirch in vielen Gedichten gethan hat, die man ſich aber dem Jnnhalte und der Schreib-Art nach nicht zum Muſter nehmen muß; weil es Wercke ſeiner hitzigen Jugend ſind, da er noch dem Lohenſteiniſchen Geſchmack gefolget iſt.","Die langen jambischen Verse mit ungetrennten Reimen schicken sich am besten dazu, man mag sie nun entweder in einem hintereinander fort laufen lassen, und nur zuweilen an bequemen Orten einen Absatz machen, oder auch acht oder zehnzeilichte Strophen machen, wie Neukirch in vielen Gedichten getan hat, die man sich aber dem Innhalte und der Schreibart nach nicht zum Muster nehmen muß ; weil es Werder seiner hitzigen Jugend sind, da er noch dem Lohensteinischen Geschmack gefolget ist."
2,"Es iſt bereits oben bey andrer Gelegenheit gedacht worden, daß Cicero das Gegentheil angemercket, wenn er erzehlt, daß Jſocrates den Poeten vieles abgelernet, was zur Lieblichkeit einer Rede was beytragen kan.","Es ist bereits oben bei anderer Gelegenheit gedacht worden, daß Cicero das Gegenteil angemerkt, wenn er erzählt, daß Aristokrates den Poeten vieles abgelernt, was zur Lieblichkeit einer Rede was beitragen kann."
3,Genug er that jenen kein Unrecht.,Genug er tat jenen kein Unrecht.
4,Hume.,Hume.
5,"Der Koͤnigin Annæ in Engeland Leib-Medicus, Martinus Lyſter, hat einen Tractat de humoribus geſchrieben, welches Buch Leibniz auch æſtimiret.","Der Königin Annae in Engeland Leib - Medikus, Martinus Lyster, hat einen Traktat de humoribus geschrieben, welches Buch Leibniz auch ästimieret."
6,"Es wird in dieſem Tractate gehandelt von der Muͤntze Alterthum und Aufkommen, Gerechtigkeitſelbige zu ſchlagen, und deren unterſchiedlichen Arten, als Hebraͤiſchen, Chaldaͤiſchen, Perſiſchen, Griechiſchen, Roͤmiſchen, alten und neuen Teutſchen, wie nicht weniger allen ietzo gangbahren guͤldenen und ſilbernen Muͤntzen, welche alle in Kupffer geſtochen mit beygefuͤget, ingleichen vom Amt und Pflicht der Muͤntzer, Aender- und Verwandlung, Auf- und Abſteigen der ſilbernen und guͤldenen Muͤntzen, ſamt dem Nutzen der Muͤntz-Probations und Valoations Taͤge.","Es wird in diesem Traktate gehandelt von der Münze Altertum und Aufkommen, Gerechtigkeitselbige zu schlagen, und deren unterschiedlichen Arten, als Hebräischen, Chaldäischen Griechischen, Römischen, alten und neuen Deutschen, wie nicht weniger allen jetzt gangbahren güldenen und silbernen Münzen, welche alle in Kupfer gestochen mit beigefügt, ingleichen vom Amt und Pflicht der Münder, Änderung, Auf und Verwandlung, Auf - und verwandlungen zu bestehen."
7,"Da ich ſolche aber ſelbſt aus den Beobachtungen fuͤr mich aufgeſucht, ſo ſey es mir auch erlaubt, ſie auf meine eigene Art herzuſetzen.","Da ich solche aber selbst aus den Beobachtungen für mich aufgesucht, so sei es mir auch erlaubt, sie auf meine eigene Art herzusetzen."
8,"Die Köpfe sind schön, und bei aller, selbst idealischen, Schönheit, dennoch mit Nationalzügen und mit lieblicher Individualität, rein und unmittelbar aus der lebendigen Natur, verwebt.","Die Köpfe sind schön, und bei aller, selbst idealischen, Schönheit, dennoch mit Nationalzügen und mit lieblicher Individualität, rein und unmittelbar aus der lebendigen Natur, verwebt."
9,"Wenn ſie nun ſolchergeſtalt zu arbeiten in Stand geſetzet ſind; ſo muͤſſen ſie gegen kuͤnftige Bezahlung mit denen erſten Materialien verſehen werden, um ihre Arbeit anfangen zu koͤnnen, davon wir ſogleich bey Gelegenheit des Manufacturhauſes in mehrern handeln werden.","Wenn sie nun solchergestalt zu arbeiten in Stand gesetzt sind ; so müssen sie gegen künftige Bezahlung mit denen ersten Materialien versehen werden, um ihre Arbeit anfangen zu können, davon wir sogleich bei Gelegenheit des Manufakturhauses in mehreren handeln werden."
10,Jener goldne Sitz Wem iſt er bereitet?,Jener goldene Sitz Wem ist er bereitet?
11,Der groſſe Kaͤyſer koͤmmt!,Der große Kaiser kommt!
12,"So habens die Griechen und Roͤmer gemacht, und ſo machens auch heute zu Tage alle Nationen.","So haben es die Griechen und Römer gemacht, und so machen es auch heute zu Tage alle Nationen."
13,"Was man aber ſonſt wider den Macchiavellum herum traͤget, das ſind lauter Weiber-Maͤhrgen.","Was man aber sonst wider den Machiavellum herum trägt, das sind lauter Weiber - Märchen."
14,"Die Pferdeſteine geben ebenfalls eine Menge alkaliſchen Geiſtes, ein ſchwarzes Oehl, und eine Erde von ſich, welche zu einer Erde zerfaͤllt .","Die Pferdesteine geben ebenfalls eine Menge alegarischen Geistes, ein schwarzes Öl, und eine Erde von sich, welche zu einer Erde zerfällt."
15,MONDE T. III. hiſt. I. SAVIARD. obſ.,Monde T. III. hist. I. Saeviard. obs.
16,Sie ſtehn auf und trinten noch eins.),Sie stehn auf und trinten noch eins. )
17,Unverkennbar iſt die Einwirkung des Klima auf die Bildung des Menſchen uͤberhaupt und ſeine Einbildungskraft insbeſondre.,Unverkennbar ist die Einwirkung des Klima auf die Bildung des Menschen überhaupt und seine Einbildungskraft insbesondere.
18,"Ja, was in den Meeres-Schluͤnden, Und den allertiefſten Gruͤnden Die Natur erzeugt und ſchafft, Fuͤl’t die Wirkung deiner Kraft.","Ja, was in den Meeres - Schlünden, Und den allertiefsten Gründen Die Natur erzeugt und schafft, Füllt die Wirkung deiner Kraft."
19,"An einem Gemälde Raphaels, wo seine hohe Ahndung des Göttlichen aus den Gesichtszügen stralte, sah ich einen groſsen Kunstlehrer Proportionen bewundern!","An einem Gemälde Raffaels, wo seine hohe Ahnung des Göttlichen aus den Gesichtszügen strahlte, sah ich einen großen Kunstlehrer Proportionen bewundern!"

### 1800 to 1899

In [35]:
df1800to1899.head(20)

,orig,norm_pred
0,"Ja, mein Freund, ſagte er, ſich gegen den Pohlen wendend, in dieſer Maͤdchenſeele liegt mehr Roͤmerſinn und maͤnnliche Staͤrke, als in mancher unſrer Waffengefaͤrthen.","Ja, mein Freund, sagte er, sich gegen den Polen wendend, in dieser Mädchenseele liegt mehr Römersinn und männliche Stärke, als in mancher unserer Waffengefährten."
1,"Nous icelny Leonhard confians à plein de ses leaulté preuve d'homme et bonne diligence, et a fin mesmement que toutes despeches soient tant plus seurement et diligement dirigez et toutes choses concernans de dit office conduictes, comme il convient pour notre dit service, et le bien de nos Royaumes, Pays et Sujets a nous retenu, commis et estably, retenons, commettons et establissons par les presentes au dit Estat et office de Chief et Maistre General de nos dictes Postes etc. —","Monsieur Julian konsions an plein de ses le liberté prouisante, et a fin messement que toutes despeses sont tant plus saurerment et dileigent dirigez et toutes choses, comme il faut pour unserdité, et le bien de nos Gouvernements,és et Sujets à nous reprochet, commis et assiqui, renvoiens, commettens et assignissent par les faits et Office de chef et à chef et maistre General de nos lettres etc."
2,"Eigentümlich ist die Stellung, die das langobardische Volksrecht zu den übrigen germanischen Rechten einnimmt.","Eigentümlich ist die Stellung, die das langobardische Volksrecht zu den übrigen germanischen Rechten einnimmt."
3,"Der Hochzeitstag meines Feindes ruͤckte heran, und mit ihm wuchs meine Angſt, die mich durch die Waͤlder und uͤber die Berge trieb.","Der Hochzeitstag meines Feindes rückte heran, und mit ihm wuchs meine Angst, die mich durch die Wälder und über die Berge trieb."
4,"I, 18 . 20 .","I, 18. 20."
5,"Der Pater Gili hat aus zwei Stellen bei Torquemada (Monarquia Indiana) bündig dargethan, daß die Mexikaner den Aufguß kalt machten, und daß erſt die Spanier den Brauch einführten, die Kakaomaſſe im Waſſer zu ſieden.","Der Pater Gili hat aus zwei Stellen bei Torquemada ( Monarquiia Indiana ) bündig dargetan, daß die Mexikaner den Aufguß kalt machten, und daß erst die Spanier den Brauche einführten, die Kakaomasse im Wasser zu sieden."
6,Stamm darf nicht verwechſelt werden mit Race oder mit Nationalität.,Stamm darf nicht verwechselt werden mit Race oder mit Nationalität.
7,"Im erwachſenen Zuſtande fehlt allen Froſchlurchen der Schwanz durchaus, während ſie, wie wir ſchon früher ſahen, im jugendlichen Zuſtande ſtets einen ſolchen beſitzen und bei manchen Gattungen dieſer Schwanz nur ſehr ſpät und lange nach vollſtändiger Entwickelung der Beine abfällt, ſo daß zuweilen ſelbſt die ausgebildete Larve eine bedeutendere Körpermaſſe bietet, als das erwachſene ſchwanzloſe Thier.","Im erwachsenen Zustande fehlt allen Froschlurchen der Schwanz durchaus, während sie, wie wir schon früher sahen, im jugendlichen Zustande stets einen solchen besitzen und bei manchen Gattungen dieser Schwaz nur sehr spät und lange nach vollständiger Entwicklung der Beine abfällt, so daß zuweilen selbst die ausgebildete Larve eine bedeutendere Körpermasse bietet, als das erwachsene schwanzlose Tier."
8,Gottſchalk!,Gottschalk!
9,Hier wird uns daher blos die letztere beschäftigen.,Hier wird uns daher bloß die letztere beschäftigen.
10,"Heuglin gibt an, daß die Neſter zuweilen noch viel größer ſeien, nämlich 5 bis 8 Fuß Länge und 3 bis 5 Fuß Breite und Höhe erreichen können.","Heuglin gibt an, daß die Nester zuweilen noch viel größer seien, nämlich 5 bis 8 Fuß Länge und 3 bis 5 Fuß Breite und Höhe erreichen können."
11,(Kann vor Weinen nicht mehr weiter reden.) Amtmann.,( Kann vor Weinen nicht mehr weiter reden. ) Amtmann.
12,Im einzelnen entfaltet sich nun unser Rechtsinstitut wie folgt.,Im Einzelnen entfaltet sich nun unser Rechtsinstitut wie folgt.
13,1766.,1761.
14,"Die Thür des Käfigs muß von oben nach unten fallen, damit ſie von ſelbſt ſchließt, wenn man vergißt, ſie zuzumachen; ſie muß auch ſo breit ſein, daß man das Sauf- und Badenäpfchen hineinſchieben kann.","Die Tür des Käfigs muß von oben nach unten fallen, damit sie von selbst schließt, wenn man vergißt, sie zuzumachen ; sie muß auch so breit sein, daß man das Sauf und Badenäpfchen hineinschieben kann."
15,"Und endlich den runden Taſchenkrebs, die eigentliche Krabbe, die alle Meeresküſten als poſſierlicher Kobold belebt und meiſt nur vom Volke gegeſſen wird, während ſie in der Delikateßhandlung fehlt.","Und endlich den runden Taschenkrebs, die eigentliche Krabbe, die alle Meeresküsten als possierlicher Kobold belebt und meist nur vom Volke gegessen wird, während sie in der Delikatessehandlung fehlt."
16,"Thatsächlich geschieht viel mehr und ist viel mehr als berechtigt allgemein anerkannt in dem Sinne, daß die Hinderung daran als ein Eingriff in die Freiheit empfunden werden würde, der als Unrecht abzuwehren und aufzuheben ist.","Tatsächlich geschieht viel mehr und ist viel mehr als berechtigt allgemein anerkannt in dem Sinne, daß die Hinderung daran als ein Eingriff in die Freiheit empfunden werden würde, der als Unrecht abzuwehren und aufzuheben ist."
17,"Aus den vorstehenden Beobachtungen an Pinguicula lusitanica sehen wir, dasz die schon naturgemäsz bedeutend eingekrümmten Ränder der Blätter durch die Berührung mit organischen und anorganischen Körpern dazu gereizt werden, sich noch weiter einwärts zu krümmen; dasz Eiweisz, Kohlsamen, Stückchen von Spinatblättern und Glassplitter es verursachen, dasz die Drüsen reichlicher absondern; — dasz Eiweisz von dem Secrete aufgelöst wird, und dasz Kohlsamen von ihm getödtet werden; — und endlich, dasz Substanz aus den Insecten, welche mittelst des klebrigen Secrets in groszer Anzahl gefangen werden, von den Drüsen aufgesaugt wird.","Aus den vorstehenden Beobachtungen an Pinygula lustiga sehen wir, dasz die schon naturgemäß bedeutend eingekrümmten Ränder der Blätter durch die Berührung mit organischen und anorganischen Körpern dazu gereizt werden, sich noch weiter einwärts zu krümmen ; dasatz Eiweis, Kohlsamen, Stückchen von Spinatblättern und Glassplitter es verursachen, daszu die Drüsen reichlicher absondern ; dasze Eiweisz von dem Sekretäre aufgelöst wird, und dasz Kohlsam von dem Korrek"
18,"Münzenpflanzen kamen in 1½ Unzen Wasser, womit 1 bis 2 Tropfen des stärksten Salpetergeistes vermischt waren, dem Anscheine nach besser, als in bloſsem Wasser, fort.","Münzenpflanzen kamen in 1 °e Unzen Wasser, womit 1 bis 2 Tropfen des stärksten Salpetergeistes vermischt waren, dem Anscheine nach besser, als in bloßem Wasser, fort."
19,Steller in Nov. comm. Petrop. T. II. p. 341.,Steller in Nov. komm. Petrop. T. II. p. 341.